version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: revanthsatyam/web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - mysql
      - shipping
      - payment
  mongodb:
    image: revanthsatyam/mongodb:v1
    container_name: mongodb
  catalogue:
    image: revanthsatyam/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
  user:
    image: revanthsatyam/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: revanthsatyam/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  mysql:
    image: revanthsatyam/mysql:v1
    container_name: mysql
  shipping:
    image: revanthsatyam/shipping:v2
    container_name: shipping
    depends_on:
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: revanthsatyam/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
  ratings:
    image: revanthsatyam/ratings:v1
    container_name: ratings
    depends_on:
      - mysql